// Generated by CoffeeScript 1.10.0
var Config, None, Transport, ref, tagged, taggedSum;

ref = require('daggy'), tagged = ref.tagged, taggedSum = ref.taggedSum;

None = require('fantasy-options').None;

Transport = taggedSum({
  Tcp: ['host', 'port'],
  Ws: ['create']
});

Config = tagged('transport', 'vhost', 'hbSendFreqMillis', 'hbRecvFreqMillis', 'credentials');

Config.noAuth = function(transport, vhost, hbSendFreqMillis, hbRecvFreqMillis) {
  return Config(transport, vhost, hbSendFreqMillis, hbRecvFreqMillis, None);
};

module.exports = {
  Transport: Transport,
  Config: Config
};
